language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project bunchofbrains-22ce9 --token "1//03UF-g7-cvM_LCgYIARAAGAMSNwF-L9IrQ6HBEFOEB9WtUbhGWnvzo3fNPE4LFXbpirRvBCBtrq0z9HosE2Fl41j29aof9pU0jkA"