language: node_js
node_js:
  - "7"
cache: npm
branches:
  only:
    - master
  except:
    - develop
jobs:
  include:
    - stage: deploy
      script:
        - npm install -g firebase-tools
        - npm run build
        - firebase deploy --project "$projectId" --token "$FIREBASE_TOKEN"